### ISSUE TITLE
problem about the bbox format

### ISSUE THREAD

**Issue by LeeBC2298** [FurkanOM/tf-ssd#2]
I need to feed my own data and I feed the data as the note under 'calculate_actual_outputs':
![image](https://user-images.githubusercontent.com/41717225/89192644-5ccf5d00-d5d7-11ea-9837-2ff34283a2fd.png)

And my data is like this:
the prior boxes:
![image](https://user-images.githubusercontent.com/41717225/89192760-93a57300-d5d7-11ea-8937-2390ee7ba98d.png)
the ground truth boxes:
![image](https://user-images.githubusercontent.com/41717225/89192822-acae2400-d5d7-11ea-8726-ec80662b391a.png)

I think my data format is correct, but I got this error:
![image](https://user-images.githubusercontent.com/41717225/89193116-15959c00-d5d8-11ea-85ed-97e3d13e856b.png)
It seems that the 'pos_cond' should be shape [batch, num_of_anchers, 4], is this caused by my data format?

**Comment by LeeBC2298** [comment]
I tried to fix my problem like this:
_pos = tf.expand_dims(pos_cond, -1)
_pos = tf.concat([_pos, _pos, _pos, _pos], axis=-1)
expanded_gt_boxes = tf.where(_pos, gt_boxes_map, tf.zeros_like(gt_boxes_map))

This worked, but met another error at bbox_utils.get_deltas_from_bboxes, so I think it may be caused by my bbox format.

**Comment by FurkanOM** [comment]
Hi, which version of tensorflow are you using?

**Comment by LeeBC2298** [comment]
> Hi, which version of tensorflow are you using?

I used tensorflow 1.15.0 and this error is probably caused by the version mismatch.
I found this warning:
![image](https://user-images.githubusercontent.com/41717225/89262344-0d823e80-d662-11ea-919d-25f57b767eba.png)
and changed tf.where to np.where, it fixed the error.
